require(rjson)

############################################################
### Add HGNC gene names to Ensembl-annotated file
############################################################

# Required config parameters (if this step is not skipped):
#
# "output_dir": "dir4"
# Path to the directory where all output files should be placed, including
# those generated by earlier steps in this post-processing

# Optional config parameters:
#
# "skip_steps": ["add-hgnc-names", ...]
# If "add-hgnc-names" is not included in the "skip_steps" list
# parameter, then it will run by default. If included,
# then this step will be skipped.
#
# "add-hgnc-names" :
# {
# 	"input_results_file": "file1",		# Optional
# 	"output_results_file": "file2",		# Optional
#
#	"ensembl_to_hgnc_map_file": "map-file"	# Optional
#	"ensembl_col_index": 1			# Required if "ensembl_to_hgnc_map_file" is specified
#	"hgnc_col_index": 2			# Required if "ensembl_to_hgnc_map_file" is specified
# }
#
# If included, "add-hgnc-names" is a JSON object that contains additional parameters
# that will be used for running this filtering step.
#
#	"input_results_file" is, optionally, the location of the input file to which the HGNC 
# 	gene names should be added. This file should be in TSV format and should
#	contain a column named "feature" that contains the Ensembl gene IDs of the
#	genes tested for colocalization. It is OK if the gene names contain version numbers,
#	e.g. "ENSG00000006071.1", where the final "1" after the period represents the gene
#	version. If version numbers are included, they will be trimmed before merging with
#	the HGNC table. If "input_results_file" is not included as a parameter, the default
#	will be to load the output from the "assign-locus-numbers" step, namely the file at
#	{output_dir}/filtered_coloc_table_with_loci.txt.
#	
#	"output_results_file" is, optionally, the file to which the output of this step
#	should be written. If not specified, it will be placed at
#	{output_dir}/filtered_coloc_with_loci_hgnc.txt.
#
#	"ensemble_to_hgnc_map_file", is, optionally, a mapping of ensembl gene IDs to
#	HGNC IDs. If specified, then two additional parameters, "ensembl_col_index" and
#	"hgnc_col_index" are required, specifying the 1-indexed column indices of the ensembl gene ID
#	and HGNC gene ID, respectively. If not specifed, the default file will be used, namely the mapping
#	data/hgnc/ensembl_to_hgnc.txt that is downloadable as part of this project.
#	TODO: Add details about how this file was obtained from BioMart
#

column_titles = c("ensembl", "hgnc")
default_column_indices=c(1,3)

main = function()
{
        # Load config file
	config_file = commandArgs(trailingOnly=TRUE)[1]
        config = validate_config(config_file)

	# Load results table
	results = load_results_table(config)

	# Get table of mappings to HGNC genes
	genes = get_gene_table(config)

	# Remove entries with duplicated Ensembl IDs
	genes = genes[!duplicated(genes$ensembl),]
	
	# Combine HGNC table with results table
	results = merge(genes, results, by.x="feature", by.y="ensembl", all.y=TRUE)

	# Write output table of results with HGNC annotations
	if (("add_hgnc_names" %in% names(config)) && ("output_results_file" %in% names(config$add_hgnc_name)))
	{
		write.table(results, config$add_hgnc_name$output_results_file, quote=FALSE, sep="\t", col.names=TRUE, row.names=FALSE)
	} else
	{
		write.table(results, file=paste(config$out_dir, "filtered_with_hgnc.txt", sep="/"), quote=FALSE, sep="\t", col.names=TRUE, row.names=FALSE)
	}

}

get_gene_table = function(config)
{
	column_indices = default_column_indices

	# Load the table of mappings from Ensembl to HGNC
	if (("add-hgnc-names" %in% config) && ("ensemble_to_hgnc_map_file") %in% names(config$add_hgnc_names))
	{
		# If using a custom file, get the desired column indices too
		genes = read.table(paste(config$output_dir, config$add_hgnc_names$ensemble_to_hgnc_map_file, sep="/"), header=TRUE, sep="\t")
		column_indices[1] = config$add_hgnc_names$ensembl_col_index
		column_indices[2] = config$add_hgnc_names$hgnc_col_index
	}
	else
	{
		genes = read.table("data/hgnc/ensembl_to_hgnc.txt", header=TRUE, sep="\t")
	}

	genes = genes[,column_indices]
	colnames(genes) = c("ensembl", "hgnc")
	return(genes)
}


validate_config = function(config_file)
{
        # Load config file, specified as a command line parameter
        config = fromJSON(file=config_file)

        # Validate config file to be sure required parameters are present
        if (("add_hgnc_names" %in% names(config)))
        {
		if (("ensembl_to_hgnc_map_file" %in% names(config$add_hgnc_names)))
		{
			if (!(("ensembl_col_index" %in% names(config$add_hgnc_names)) && ("hgnc_col_index" %in% names(config$add_hgnc_names))))
			{
				stop("Config ERROR: When using a custom Ensembl-to-HGNC mapping, you
				     must specify 'ensembl_col_index' and 'hgnc_col_index' in the config file")
			}

		}
	}
	if (!("output_dir" %in% names(config)))
	{
	        stop("Config ERROR: You must specify 'output_dir' in config file")
	}

        return(config)
}

load_results_file = function(config)
{
	if ((("add_hgnc_names") %in% names(config)) && ("input_results_file" %in% names(config$add_hgnc_names)))
	{
		d = read.table(file=config$add_hgnc_names$input_results_file, header=TRUE)
	}
	else
	{
		d = read.table(file=paste(config$output_dir, "i-dont-know", sep="/"), header=TRUE)
	}

	# Quick input check
	if (!("feature" %in% colnames(d)))
	{
		stop("input error: the input coloc results table must have a 'feature' column showing Ensembl IDs")
	}

	return(d)
}

main()
