require(rjson)
require(dplyr)

############################################################
### Add HGNC gene names to Ensembl-annotated file
############################################################

# Required config parameters (if this step is not skipped):
#
# "output_dir": "dir4"
# Path to the directory where all output files should be placed, including
# those generated by earlier steps in this post-processing

# Optional config parameters:
#
# "skip_steps": ["add_hgnc_names", ...]
# If "add_hgnc_names" is not included in the "skip_steps" list
# parameter, then it will run by default. If included,
# then this step will be skipped.
#
# "add_hgnc_names" :
# {
# 	"input_results_file": "file1",		# Optional
# 	"output_results_file": "file2",		# Optional
#
#	"ensembl_to_hgnc_map_file": "map-file"	# Optional
#	"ensembl_col_index": 1			# Required if "ensembl_to_hgnc_map_file" is specified
#	"hgnc_col_index": 2			# Required if "ensembl_to_hgnc_map_file" is specified
# }
#
# If included, "add_hgnc_names" is a JSON object that contains additional parameters
# that will be used for running this filtering step.
#
#	"input_results_file" is, optionally, the location of the input file to which the HGNC 
# 	gene names should be added. This file should be in TSV format and should
#	contain a column named "feature" that contains the Ensembl gene IDs of the
#	genes tested for colocalization. It is OK if the gene names contain version numbers,
#	e.g. "ENSG00000006071.1", where the final "1" after the period represents the gene
#	version. If version numbers are included, they will be trimmed before merging with
#	the HGNC table. If "input_results_file" is not included as a parameter, the default
#	will be to load the output from the "assign_locus_numbers" step, namely the file at
#	{output_dir}/filtered_coloc_table_with_loci.txt.
#	
#	"output_results_file" is, optionally, the file to which the output of this step
#	should be written. If not specified, it will be placed at
#	{output_dir}/filtered_coloc_with_loci_hgnc.txt.
#
#	"ensemble_to_hgnc_map_file", is, optionally, a mapping of ensembl gene IDs to
#	HGNC IDs. If specified, then two additional parameters, "ensembl_col_index" and
#	"hgnc_col_index" are required, specifying the 1-indexed column indices of the ensembl gene ID
#	and HGNC gene ID, respectively. If not specifed, the default file will be used, namely the mapping
#	data/hgnc/ensembl_to_hgnc.txt that is downloadable as part of this project.
#	TODO: Add details about how this file was obtained from BioMart
#

add_hgnc_names = function(config_file, input_file, output_file)
{
	config = fromJSON(file=config_file)$add_hgnc_names
	config$input_file = input_file
	config$output_file = output_file

	# Load results table
	results = load_results_file_for_hgnc(config)

	# Get table of mappings to HGNC genes
	genes = get_hgnc_table(config)

	# Remove entries with duplicated Ensembl IDs
	genes = genes[!duplicated(genes$ensembl),]
	
	# Combine HGNC table with results table
	results = merge(genes, results, by="ensembl", all.y=TRUE)
	results$hgnc = as.character(results$hgnc)
	results$ensembl = as.character(results$ensembl)
	results$hgnc[is.na(results$hgnc)] = results$ensembl[is.na(results$hgnc)]
	results$hgnc[results$hgnc == ""] = results$ensembl[results$hgnc == ""]

	write.table(results, config$output_file, col.names=TRUE, row.names=FALSE, sep="\t", quote=FALSE)
}

get_hgnc_table = function(config)
{

	# Load the table of mappings from Ensembl to HGNC	
	column_indices = as.numeric(c(config$ensembl_col_index, config$hgnc_col_index))
	genes = read.table(config$ensemble_to_hgnc_map_file, header=TRUE, sep="\t")

	genes = genes[,column_indices]
	colnames(genes) = c("ensembl", "hgnc")
	return(genes)
}

load_results_file_for_hgnc = function(config)
{
	data = read.table(file=config$input_file, header=TRUE)

	# Quick input check
	if (!("ensembl" %in% colnames(data)))
	{
		stop("input error: the input coloc results table must have an 'ensembl' column showing Ensembl IDs")
	}

	data$ensembl = substring(data$ensembl, 1, 15)

	return(data)
}

args = commandArgs(trailingOnly=TRUE)

config_file = args[1]
input_file = args[2]
output_file = args[3]
add_hgnc_names(config_file, input_file, output_file)
